### ISSUE TITLE
bboxes sometimes returns nothing.

### ISSUE THREAD

**Issue by Mech7** [sunng87/node-geohash#24]
I am drawing the bounding boxes on google map and there are certain cases where the bboxes returns nothing while it should.
For example
```
//  precision; 1
// google maps zoom; 4
// returns nothing
geo.bboxes(-50.077637397640146, 100.810015625, 1.0336827697921598, -179.385296875, 1)

//  precision; 1
// google maps zoom; 4
// returns 6
geo.bboxes(-49.51027862137093, 99.6674375, 1.912289970207342, 179.472125, 1);
```

With higher precision this becomes even more clear on certain coordinates.

**Comment by sunng87** [comment]
The bboxes function takes arguments as `minLat, minLon, maxLat, maxLon`. Please try to correct and run again.

**Comment by Mech7** [comment]
Ah i think this is because google maps get bounds is returning something incorrect due to wrapping
