### ISSUE TITLE
Will bboxes work near the meridians/equator

### ISSUE THREAD

**Issue by tracker1** [sunng87/node-geohash#25]
I only ask, and it probably won't affect me (or most).. but notice that the geocode-js demo had problems with locations near the anti-meridian.

https://github.com/davetroy/geohash-js
http://openlocation.org/geohash/geohash-js

beringovsky - 3 for matching
kabara island - 3 matching

**Comment by arjunmehta** [comment]
@tracker1 Would you be able to post a more specific example of coordinate ranges that you'd like to test? Or perhaps try it out to see if it works the way you'd expect and explain what you would expect?

`geohash.bboxes()` will return bboxes if you provide coordinate ranges up to – but not over – the anti-meridian.

For example:
```javascript
var bboxes = geohash.bboxes(0, 180-0.001, 0, 180, 8);
// ==> [ 'rzzzzzzr', 'rzzzzzzx', 'rzzzzzzz' ]
```
Is the same as:
```javascript
var bboxes = geohash.bboxes(0, 180-0.001, 0, 180+0.001, 8);
// ==> [ 'rzzzzzzr', 'rzzzzzzx', 'rzzzzzzz' ]
```
It seems like the boxes past 180 are ignored. So, currently, If you want to have all bboxes passing over the antimeridian you'll need to concat two arrays...

```javascript
// var bboxes = geohash.bboxes(0, 180-0.001, 0, 180+0.001, 8);
var bboxes = geohash.bboxes(0, 180-0.001, 0, 180, 8);
bboxes = bboxes.concat(geohash.bboxes(0, 0, 0, 0.001, 8))
// ==> [ 'rzzzzzzr',  'rzzzzzzx',  'rzzzzzzz',  '7zzzzzzz',  'kpbpbpbp',  'kpbpbpbr',  'kpbpbpbx' ]
```

We may be able to handle these edge cases by trying to be smart about the range inputs. @sunng87 ?

**Comment by arjunmehta** [comment]
@tracker1 Also, the equator shouldn't be a problem, but you may encounter a similar issue at the north and south poles.

**Comment by tracker1** [comment]
@arjunmehta  Thanks.. I'm sorry if the question wasn't precise.. I just wanted to know if there would be an issue finding neighbors when near the antimerridian... and as pointed out the poles too... 

There are very few locations where it would really be an issue, just the same it's good to know... and would suggest adding a comment in the documentation as such.

**Comment by sunng87** [comment]
@arjunmehta Thanks for explanation. Actually the geohash library could not deal with longitude larger than 180. `180.01` is actually `179.99`:

```
> g.bboxes(0, 179.99, 0, 180, 7)
[ 'rzzzzzb',
  'rzzzzzc',
  'rzzzzzf',
  'rzzzzzg',
  'rzzzzzu',
  'rzzzzzv',
  'rzzzzzy',
  'rzzzzzz' ]
> g.bboxes(0, -180.0, 0, -179.99, 7)
[ '2pbpbpb',
  '2pbpbpc',
  '2pbpbpf',
  '2pbpbpg',
  '2pbpbpu',
  '2pbpbpv',
  '2pbpbpy',
  '2pbpbpz' ]
```

**Comment by sunng87** [comment]
Close it for now, and if you have any questions feel free to reopen it. :-)
