### ISSUE TITLE
Bit depth does not have to be even

### ISSUE THREAD

**Issue by christjt** [sunng87/node-geohash#27]
In the readme under **geohash.encode_int** it is stated that bit depth must be even, this is not the case as this would simply mean that the longitude and latitude would have differing precision/error. The code handles this perfectly fine, so I assume it is just a type-o or something you forgot to omit.

**Comment by pjarts** [comment]
The decode_int method can't handle odd bit depths as it decodes the bits in pairs. I guess that's why the readme states it has to be even.

**Comment by sunng87** [comment]
The longitude and latitude has different value range (-180-180 vs -90-90) so there is always one more bit for longitude. That's why the depth need to be even.
