### ISSUE TITLE
ngeohash@0.6.1 installation failed on react-native

### ISSUE THREAD

**Issue by haialaluf** [sunng87/node-geohash#35]
I am trying to install ngeohash@0.6.1 on react-native app, and it fails with this error:

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngeohash@0.6.1 install: `browserify . -o ngeohash.js -s ngeohash`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ngeohash@0.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/haialaluf/.npm/_logs/2018-12-16T15_36_52_892Z-debug.log

What I had to do is installing the module using `--ignore-scripts`.
ngeohash@0.6.0 works just fine.

**Comment by p-3** [comment]
same for me..

**Comment by arjunmehta** [comment]
@haialaluf @p-3 Can you perhaps show us the content of your install log?

Also can you tell us which version of node and npm you are using.

I think I found the issue and have created a PR https://github.com/sunng87/node-geohash/pull/36

@sunng87 I think this is due to the latest PR, where @ovider used ES6 `const` instead of `var` for initializing variables.

**Comment by sunng87** [comment]
@arjunmehta thanks for the fix. I will create a new release later today.

**Comment by hendrikmoree** [comment]
Since today my install also fails with: `sh: browserify: command not found`

We use ngeohash in our node project as a dependency. When I try to install all dependencies, we got this error. Because browserify is just a dev-dependency of you project it's not installed. Can you fix that too?

**Comment by benoitvidis** [comment]
you can easilly reproduce the issue by trying to install the package from a fresh docker container

```
docker run -ti --entrypoint bash node:8
root@881e87d28e10:/# npm i -g ngeohash

> ngeohash@0.6.1 install /usr/local/lib/node_modules/ngeohash
> browserify . -o ngeohash.js -s ngeohash

sh: 1: browserify: not found
```

**Comment by benoitvidis** [comment]
Using the same container, the last release now installs without error.
Thank you!

**Comment by sunng87** [comment]
Thanks!
