### ISSUE TITLE
Can I change MIN/MAX_LAT/LON to suit my custom "map"

### ISSUE THREAD

**Issue by gcleaves** [sunng87/node-geohash#43]
I have a custom map which is just a rectangular CSS button and I want to map button clicks on the coordinates. Can I safely change the MIN_LAT, etc. constants in the library and will it just work correctly?

**Comment by sunng87** [comment]
It's possible but you should keep your `(max_lat - min_lat) * 2 == (max_lon - min_lon)`.

I'm not going to add API for this case. Just fork the repo and change the constants by yourself.
